name: Consume
description: Consume dispatched vars

inputs:
  client-payload:
    description: The payload to send with the event
    required: true
    default: "{}"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: target
  color: gray-dark
