name: "Build"

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install @actions/core

      - name: Build project
        run: yarn build
        